part2: 
	gcc -o add-voter-tcp add-voter-tcp.c
	gcc -o change-password-tcp change-password-tcp.c
	gcc -o list-candidates-tcp list-candidates-tcp.c
	gcc -o server-tcp server-tcp.c
	gcc -o view-result-tcp view-result-tcp.c
	gcc -o vote-count-tcp vote-count-tcp.c
	gcc -o vote-tcp vote-tcp.c
	gcc -o vote-zero-tcp vote-zero-tcp.c
