part1: 
	gcc -o add-voter-udp add-voter-udp.c
	gcc -o change-password-udp change-password-udp.c
	gcc -o list-candidates-udp list-candidates-udp.c
	gcc -o server-udp server-udp.c
	gcc -o view-result-udp view-result-udp.c
	gcc -o vote-count-udp vote-count-udp.c
	gcc -o vote-udp vote-udp.c
	gcc -o vote-zero-udp vote-zero-udp.c
